### ISSUE TITLE
The widget doesn't work

### ISSUE THREAD

**Issue by bonbonboi** [AntiNeko/CatBoxForAndroid#13]
Hello
I'd like to report that the widget doesn't work. Thanks

**Comment by xchacha20-poly1305** [comment]
Please provide more information.

**Comment by bonbonboi** [comment]
When I tap the widget it says "app isn't installed"

**Comment by xchacha20-poly1305** [comment]
> When I tap the widget it says "app isn't installed"

Which program said it?

**Comment by bonbonboi** [comment]
CatBox.

**Comment by xchacha20-poly1305** [comment]
If you are using plugin, please install it.

**Comment by bonbonboi** [comment]
I don't use any plugin. Since you have closed this issue I'm going to use nekobox because its widget is working fine. Thanks
