### ISSUE TITLE
BUG: 备份导入bug 百分百复现

### ISSUE THREAD

**Issue by bxoooooo** [AntiNeko/CatBoxForAndroid#15]
## 描述问题

预期行为：导入备份设置  路由 分组

实际行为：导入以上备份后点击启动直接转圈卡死

## 如何复现

先备份所有数据  分组设置 路由    删除app重新导入

单独导入节点分组正常

**Comment by bxoooooo** [comment]
确定来自catbox

**Comment by bxoooooo** [comment]
难道github  和  F-DROID 不是互通吗

**Comment by xchacha20-poly1305** [comment]
F-Droid 版本更新会落后一点，不保证跨版本兼容。
