### ISSUE TITLE
ECH from Cloudflare

### ISSUE THREAD

**Issue by imagecreation1** [AntiNeko/CatBoxForAndroid#19]
Hi guys.
I have a free Cloudflare account with a domain. Is there a way to not generate my own ECH key with Singbox, but use the existing ECH config from Cloudflare? How could I get -----BEGIN ECH CONFIGS----- lines?
Thanks in advance!

**Comment by xchacha20-poly1305** [comment]
It seems that cloudflare does not privide HTTPS DNS records for ECH... Let me do some research...

**Comment by xchacha20-poly1305** [comment]
Generally speaking, ECH works with HTTPS DNS records.You can check if your server has HTTPS records here.(https://dns.google/query?name=crypto.cloudflare.com&rr_type=HTTPS&ecs=)

If you see the records include "ech=\*", then you can enabled ECH in TLS settings. If not, you can't.

**Comment by imagecreation1** [comment]
OK, thanks, I found that you can also use the 
drill HTTPS _domain.com_ 
command to check if there are any ech= entries.
Oh, and yes, cloudflare just disabled all ech= because of their bugs. - https://community.cloudflare.com/t/early-hints-and-encrypted-client-hello-ech-are-currently-disabled-globally/567730
